return {
    kill_elite = "wwise/events/player/play_elite_killed",
    kill_special = "wwise/events/player/play_special_killed",
    kill_monster = "wwise/events/player/play_monster_killed",
    purchase_aquila = "wwise/events/ui/play_ui_npc_interacts_premium_vendor_purchase_aquilas",
    purchase_item = "wwise/events/ui/play_ui_stores_shared_buy",
    acquire_currency = "wwise/events/ui/play_hud_notifications_credits_received",
    acquire_currency_eor = "wwise/events/ui/play_ui_eor_currency_credits_stop",
    acquire_item_tier_1 = "wwise/events/ui/play_hud_notifications_item_tier_1",
    acquire_item_tier_2 = "wwise/events/ui/play_hud_notifications_item_tier_2",
    acquire_item_tier_3 = "wwise/events/ui/play_hud_notifications_item_tier_3",
    overheat_high = "wwise/events/weapon/play_plasmagun_overheat_intensity_01",
    overheat_critical = "wwise/events/weapon/play_plasmagun_overheat_intensity_02",
    backstab_melee = "wwise/events/player/play_indicator_backstab_melee",
    backstab_ranged = "wwise/events/player/play_indicator_backstab_ranged",
    player_join = "wwise/events/ui/play_ui_mission_lobby_matchmade_players_join",
    player_ready = "wwise/events/ui/play_ui_mission_lobby_ready_up",
    crafting_upgrade = "wwise/events/ui/play_ui_npc_interacts_forge_upgrade_item",
    crafting_reroll = "wwise/events/ui/play_ui_npc_interacts_forge_reroll_perk",
    crafting_extract = "wwise/events/ui/play_ui_npc_interacts_forge_extract_trait",
    crafting_fuse = "wwise/events/ui/play_ui_npc_interacts_forge_fuse_traits",
    crafting_replace = "wwise/events/ui/play_ui_npc_interacts_forge_replace_trait",
    social_send = "wwise/events/ui/play_ui_social_send",
    social_receive = "wwise/events/ui/play_ui_social_receive",
    social_block = "wwise/events/ui/play_ui_social_block",
}